### ISSUE TITLE
8 players game goes to turn 10 with one player with only one card

### ISSUE THREAD

**Issue by Maxouwell** [AmirRezaM75/skullking#11]
Hello, 

On a game we just made, there was a player with only 8 card turn 9 and 1 card turn 10.
The game crashed on turn 10 with a 500 error.

Also, we can't start a game anymore, may be related.

**Comment by AmirRezaM75** [comment]
Hi @Maxouwell 
How many players were in the game?

**Comment by AmirRezaM75** [comment]
Hi @Maxouwell 
The allowed max player for the game is 7. I made a mistake to check that before starting the game.
Sorry to ruined your game.

**Comment by Maxouwell** [comment]
Thanks for your response !
In the rules we have, the last round(s) are just played with the same number of cards.

So :
* for 8 players, rounds 8, 9 and 10 are all played with 8 cards,
* for 9 and 10 players, round 7, 8, 9 and 10 are all played with 7 cards

It may be a way to open the max number of players.

**Comment by AmirRezaM75** [comment]
There are 71 cards in total.

```
Parrot (14)
Pirate Map (14)
Treasure Chest (14)
Jolly Roger (14)
Pirate (5)
Skull King (1)
Mermaid (2)
Escape (5)
Kraken (1)
White Whale (1)
```
This is from the official rule book:
> Skull King is played over 10 rounds. 1 card is dealt to each player in the first round, 2 are dealt in the second, and so on, ending with 10 cards dealt to each player in round 10. The entire deck, including all cards played in the previous round, is shuffled at the start of each round.

I think you are talking about advanced rules:
> When playing with more than six players, ensure that each player has the same number of cards in the final rounds. Simply repeat the number of cards dealt, which allows each player to have an equal number of cards, in each of the remaining final rounds.

I need to take a look at my entire game logic before implementing that. It takes time.

**Comment by AmirRezaM75** [comment]
Sorry @Maxouwell 
Unfortunately, implementing this feature would require extensive changes to the source code. Additionally, we recently introduced our new bot feature, which is currently trained to handle a maximum of 7 players. I'll revisit this issue and reopen it if we find a viable solution.
