### ISSUE TITLE
[Feature] Add a annoncement page with total binding

### ISSUE THREAD

**Issue by Maxouwell** [AmirRezaM75/skullking#12]
What would be interesting is a annoncement between the binding phase and the tricks phase, which display the total bidding for all the player vs the number of hand winnable.

Something like "10 bids for 4 tricks" in large size for a couple of seconds.

Alternatively, it could be displayed at the top of the players bar.

**Comment by AmirRezaM75** [comment]
Hey @Maxouwell 
Now we show total bid at top of sidebar

![Screenshot from 2024-07-29 19-51-24](https://github.com/user-attachments/assets/d10ef5d0-4043-4ecc-a167-3d1941e66274)

R: https://github.com/AmirRezaM75/skullking/issues/13
