### ISSUE TITLE
Whale behavior

### ISSUE THREAD

**Issue by depesz** [AmirRezaM75/skullking#19]
Let's consider case where, in one hand, we have only Whale, figures (like Pirate), and escapes.

As far as I understand the rules, all the cards should be treated as escapes, and first person that played escape should win the hand.

Currently in such case, as far as I can tell, noone wins the hand.

I think it's a bug, but if it's too difficult to fix, or you can show me my misunderstanding of rules, I'll happily accept current situation :)

**Comment by AmirRezaM75** [comment]
It's not bug

This is from official rule book

> If only special cards were played, then the trick is discarded (like the Kraken)

![Screenshot from 2024-07-30 18-27-13](https://github.com/user-attachments/assets/5a8380bd-cd80-4171-85f3-d46aecfce581)

**Comment by depesz** [comment]
Ha. Missed that. Thanks again.

**Comment by AmirRezaM75** [comment]
No worry, 
You're welcome :raised_hands:
