### ISSUE TITLE
Unable to see all deck on small laptop screen

### ISSUE THREAD

**Issue by simonbotte** [AmirRezaM75/skullking#20]

**Comment by AmirRezaM75** [comment]
@simonbotte Can you send an screenshot?
Currently you can scroll to left and right

**Comment by simonbotte** [comment]
My bad, I thought that it would be an overflow and not a slider. Sorry

**Comment by AmirRezaM75** [comment]
@simonbotte No problem. Feel free to report any inconvenience.
