### ISSUE TITLE
How to disable auto-play?

### ISSUE THREAD

**Issue by depesz** [AmirRezaM75/skullking#24]
Sorry, but the autoplay feature is beyond irritating. We often play purposedly slower, because there is no way to pause the game, and it happens that some player(s) need to step away from computer for a moment,

Please, please, please, pretty please - allow disabling of autoplay. We want to feel that we play, and are not passive observers of ai doing stuff (I know it's not what's happening, but the feeling is there).

**Comment by DSilva27** [comment]
Was going to raise the same issue. This feature sucks. It will make us stop playing.

**Comment by depesz** [comment]
It already did stop us. We normally play at least 3-4 games. This time we stopped at 6th hand of first game :(

**Comment by AmirRezaM75** [comment]
Hey
I disabled that feature.
It was one of the user's request.
Thanks for feedback

**Comment by depesz** [comment]
Thank you very much. Definitely appreciated.

**Comment by AmirRezaM75** [comment]
your welcome

**Comment by DSilva27** [comment]
That's amazing, thank you!
