### ISSUE TITLE
Friend from canada is constantlu diosconnected, but only from lobby?

### ISSUE THREAD

**Issue by depesz** [AmirRezaM75/skullking#25]
Hi,
we play some skull king, and recently our friend from Canada (most of us are in Poland) noticed that she gets disconnected from lobby *a lot* - like every minute or so.
is there something that can be checked in logs? Her username is "Akinara", and aside from this problem, all seems to work well.

Thanks, and again: amazing work!

**Comment by AmirRezaM75** [comment]
Hey
Hope you are doing well.
Can you send me the screenshot when she got disconnected?
Also the browser name and its version?
Is she opening multiple tabs (for SkullKing)  at the same time?

**Comment by depesz** [comment]
Hi,
so it's Firefox 131.0, 64-bit, on Windows 11 Home.
We just tried, so almost immediately after connecting to lobby, she got connection error, like the one:
![image](https://github.com/user-attachments/assets/e6487c6c-878b-48b4-9034-8f0514c3368d)

From "join lobby" to connection error, maybe 5 seconds have passed.

**Comment by AmirRezaM75** [comment]
I simulated the site and checked it with [Lamdatest](https://app.lambdatest.com/) site however I didn't receive any error.
But in my logs I do have connection errors for mentioned user.
Can she try in incognito (private) mode? maybe some extensions causing that.

**Comment by depesz** [comment]
I'll pass the information, we'll see how that will work out. But testing might take a while (work and time zone difference).

**Comment by depesz** [comment]
We tried to test it yesterday, but disconnects didn't happen?! Maybe it's something with internet connectivity? Perhaps the app could retry connection if the connection dropped?

**Comment by depesz** [comment]
The problem seems to be mostly gone, I think it was something with the internet connection of my friend. I think this can be closed. Thanks, and sorry for noise :)

**Comment by AmirRezaM75** [comment]
No problem
I wanted to confirm that with you, and you replied sooner :)

Did you check out the bot feature?

**Comment by depesz** [comment]
> bot feature

No, didn't notice it when we played last time, will test it next time.

Thanks for continuing development :)
